#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title: 2024 ESA SEEDS GIS Workshop
author: Carissa DeRanek & Jonathan Pando Ocón, PhD
logo: img/logo/logo.png
copyright: "2024"

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://jpocon.github.io/
  repository_provider: github
  path_to_book: 2024-ESA-SEEDS-GIS
  branch: main

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: github
    html_context:
      url: https://github.com/jpocon/
      path_to_book: 2024-ESA-SEEDS-GIS
      branch: main

repository:
  url: https://github.com/jpocon/2024-ESA-SEEDS-GIS/
html:
  use_repository_button: true
